# Generated by Django 5.2.10 on 2026-01-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('MCMV', 'Minha Casa Minha Vida'), ('MEDIO', 'Médio Padrão'), ('ALTO', 'Alto Padrão')], max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(default='São Paulo', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
        migrations.CreateModel(
            name='Instalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, help_text='Classe do FontAwesome (ex: fas fa-swimming-pool)', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Instalação',
                'verbose_name_plural': 'Instalações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/')),
                ('principal', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Imagem do Imóvel',
                'verbose_name_plural': 'Imagens dos Imóveis',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='imovel',
            name='instalacoes',
            field=models.ManyToManyField(blank=True, related_name='imoveis', to='imoveis.instalacao'),
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area_m2', models.PositiveIntegerField()),
                ('quartos', models.PositiveIntegerField()),
                ('banheiros', models.PositiveIntegerField()),
                ('suites', models.PositiveIntegerField()),
                ('vagas', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='ImagemUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='unidades/')),
                ('principal', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveis.unidade')),
            ],
            options={
                'verbose_name': 'Imagem da Unidade',
                'verbose_name_plural': 'Imagens das Unidades',
                'ordering': ['ordem'],
            },
        ),
    ]
