# Generated by Django 5.2.10 on 2026-01-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('MCMV', 'Minha Casa Minha Vida'), ('MEDIO', 'Médio Padrão'), ('ALTO', 'Alto Padrão')], max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(default='São Paulo', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/')),
                ('principal', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveis.imovel')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Apto 45m² - 2 dorm', max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area_m2', models.PositiveIntegerField()),
                ('quartos', models.PositiveIntegerField()),
                ('suites', models.PositiveIntegerField(default=0)),
                ('banheiros', models.PositiveIntegerField()),
                ('vagas', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido')], default='DISPONIVEL', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='imoveis.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='unidades/')),
                ('principal', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveis.unidade')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
