# Generated by Django 5.2.10 on 2026-01-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='status',
        ),
        migrations.AddField(
            model_name='unidade',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='suites',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='vagas',
            field=models.PositiveIntegerField(),
        ),
    ]
