# Generated by Django 5.2.10 on 2026-01-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemimovel',
            options={'ordering': ['-principal', 'ordem'], 'verbose_name': 'Imagem do Imóvel', 'verbose_name_plural': 'Imagens dos Imóveis'},
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
