# Generated by Django 5.2.10 on 2026-01-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_alter_imagemimovel_options_imovel_numero_imovel_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='uf',
            field=models.CharField(default='SP', max_length=2, verbose_name='UF'),
        ),
    ]
