# Generated by Django 5.2.10 on 2026-01-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imovel_suites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemimovel',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='imagemimovel',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
