# Generated by Django 5.2.10 on 2026-01-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_alter_imagemimovel_options_imagemimovel_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
