# Generated by Django 5.2.10 on 2026-01-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='bairro_oficial',
            field=models.CharField(blank=True, help_text='Bairro de registro (ex: Cidade Monções)', max_length=100, null=True, verbose_name='Bairro (Oficial)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro (Comercial)'),
        ),
    ]
