# Generated by Django 5.2.10 on 2026-01-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_imovel_bairro_oficial_alter_imovel_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('PLANTA', 'Na Planta'), ('PRONTO', 'Pronto Para Morar')], default='PLANTA', max_length=20, verbose_name='Status da Obra'),
        ),
    ]
