# Generated by Django 5.2.10 on 2026-01-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_imovel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='is_orulo',
            field=models.BooleanField(default=False, verbose_name='Importado da Órulo'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='orulo_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Órulo'),
        ),
    ]
