# Generated by Django 5.2.10 on 2026-01-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_imovel_is_orulo_imovel_orulo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='removido_na_origem',
            field=models.BooleanField(default=False, verbose_name='Removido na Órulo'),
        ),
    ]
