# Generated by Django 5.2.10 on 2026-01-16 02:05

import imoveis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_imovel_removido_na_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemimovel',
            name='imagem',
            field=models.ImageField(upload_to=imoveis.models.get_imovel_upload_path),
        ),
        migrations.AlterField(
            model_name='imagemunidade',
            name='imagem',
            field=models.ImageField(upload_to=imoveis.models.get_unidade_upload_path),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('EM_OBRA', 'Em Obras'), ('PRONTO', 'Pronto')], default='PLANTA', max_length=20, verbose_name='Status da Obra'),
        ),
    ]
