# Generated by Django 5.2.10 on 2026-01-16 03:15

import django.db.models.deletion
import imoveis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_alter_imagemimovel_imagem_alter_imagemunidade_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=imoveis.models.get_arquivo_upload_path)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('orulo_id', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Arquivo do Imóvel',
                'verbose_name_plural': 'Arquivos dos Imóveis',
            },
        ),
    ]
