# Generated by Django 5.2.10 on 2026-01-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0010_imovel_cep_imovel_latitude_imovel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Exibe este imóvel com destaque na Home e nas buscas', verbose_name='Destaque'),
        ),
    ]
