# Generated by Django 5.2.10 on 2026-02-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0014_alter_imovel_slug_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('EM_OBRA', 'Lançamento'), ('PRONTO', 'Pronto')], default='PLANTA', max_length=20, verbose_name='Status da Obra'),
        ),
    ]
