# Generated by Django 5.2.10 on 2026-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0015_alter_imovel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área Total do Terreno'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('MCMV', 'Minha Casa Minha Vida'), ('MEDIO', 'Médio Padrão'), ('ALTO', 'Alto Padrão'), ('LOTEAMENTO', 'Loteamento'), ('HARAS', 'Haras / Rural')], max_length=10),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='banheiros',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='quartos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='suites',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='vagas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
