# Generated by Django 5.2.10 on 2026-02-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0016_imovel_area_total_alter_imovel_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='titulo',
            field=models.CharField(choices=[('Apartamento', 'Apartamento'), ('Cobertura', 'Cobertura'), ('Lote/Haras', 'Lote/Haras')], default='Apartamento', max_length=255),
        ),
    ]
