# Generated by Django 5.2.10 on 2026-02-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0017_alter_unidade_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='area_laje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área da Laje'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='construtora',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Construtora'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrega'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Lançamento'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_andares',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Andares'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='total_unidades',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de Unidades'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='unidades_por_andar',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Unidades por Andar'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('EM_OBRA', 'Em Construção'), ('PRONTO', 'Pronto'), ('LANCAMENTO', 'Lançamento')], default='PLANTA', max_length=20, verbose_name='Status da Obra'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='titulo',
            field=models.CharField(choices=[('Apartamento', 'Apartamento'), ('Cobertura', 'Cobertura'), ('Lote', 'Lote')], default='Apartamento', max_length=255),
        ),
    ]
