# Generated by Django 5.2.10 on 2026-02-09 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0018_imovel_area_laje_imovel_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('BREVE', 'Breve Lançamento'), ('EM_OBRA', 'Em Construção'), ('PRONTO', 'Pronto'), ('LANCAMENTO', 'Lançamento')], default='BREVE', max_length=20, verbose_name='Status da Obra'),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
    ]
