# Generated by Django 5.2.10 on 2026-02-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0019_alter_imovel_status_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta Description para o Google', null=True, verbose_name='Descrição SEO'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Título da página', max_length=255, null=True, verbose_name='Título SEO'),
        ),
    ]
