# Generated by Django 5.2.10 on 2026-02-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0020_imovel_seo_description_imovel_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='destaque_blog',
            field=models.BooleanField(default=False, help_text='Exibe este imóvel na sidebar do Blog', verbose_name='Destaque no Blog'),
        ),
    ]
