version: '3.8'

services:
  web:
    build: .
    # O comando continua rodando o collectstatic e iniciando o Gunicorn na porta 8000
    command: sh -c "python backend/manage.py collectstatic --noinput && gunicorn --chdir backend --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/backend/media
    env_file:
      - .env
    ports:
      - "8000:8000" # Porta que você deve configurar no Forward Port do NPM
    environment:
      - DB_HOST=db
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: