server {
    listen 80;
    server_name SEU_DOMINIO_AQUI;

    client_max_body_size 50M;

    location = /favicon.ico {
        alias /var/www/imobiliaria/staticfiles/img/favicon.png;
        access_log off;
        log_not_found off;
    }

    location /static/ {
        alias /var/www/imobiliaria/staticfiles/;
    }

    location /media/ {
        alias /var/www/imobiliaria/backend/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/imobiliaria/imobiliaria.sock;
    }
}
