# Generated by Django 5.2.10 on 2026-02-13 02:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='ativo',
        ),
        migrations.AddField(
            model_name='post',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Define se o post aparece em destaque na home do blog', verbose_name='Destaque na Home'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descrição otimizada para buscadores (max 160 caracteres)', max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título otimizado para buscadores (max 70 caracteres)', max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.TextField(help_text='Use HTML para formatar o texto (Rich Text)', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='blog/capas/', verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Gerado automaticamente a partir do título', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
