# Generated by Django 5.2.10 on 2026-01-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(default='São Paulo', max_length=100)),
                ('tipo', models.CharField(choices=[('MCMV', 'Minha Casa Minha Vida'), ('MEDIO', 'Médio Padrão'), ('ALTO', 'Alto Padrão')], max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='imoveis/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
