# Generated by Django 5.2.10 on 2026-01-15 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0004_imovel_bairro_oficial_alter_imovel_bairro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo_contato', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telefone', 'Ligação')], default='whatsapp', max_length=10, verbose_name='Preferência de Contato')),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atendido', models.BooleanField(default=False)),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
