# Generated by Django 5.2.10 on 2026-01-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('texto', models.TextField(verbose_name='Acompanhamento')),
                ('proximo_passo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Próximo Passo')),
                ('data_proximo_contato', models.DateField(blank=True, null=True, verbose_name='Data do Próximo Contato')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Acompanhamento',
                'verbose_name_plural': 'Acompanhamentos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
