# Generated by Django 5.2.10 on 2026-01-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_acompanhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('em_atendimento', 'Em Atendimento'), ('visita_agendada', 'Visita Agendada'), ('proposta', 'Proposta'), ('fechado', 'Fechado (Venda)'), ('perdido', 'Perdido')], default='novo', max_length=20, verbose_name='Status do Lead'),
        ),
    ]
