# Generated by Django 5.2.10 on 2026-01-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='origem',
            field=models.CharField(default='Site', max_length=100, verbose_name='Canal de Chegada'),
        ),
    ]
