# Generated by Django 5.2.10 on 2026-02-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_email_lead_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
