# Generated by Django 5.2.10 on 2026-01-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'permissions': [('acesso_painel_admin', 'Pode acessar o painel de administração')], 'verbose_name': 'Log de Auditoria', 'verbose_name_plural': 'Logs de Auditoria'},
        ),
    ]
