name: Deploy Imobidon

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar comandos no servidor via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: garcia  # Colocamos direto aqui para garantir
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/imobiliaria
            git config core.fileMode false
            git pull origin master
            docker compose up -d --build
            docker compose exec -T web python backend/manage.py migrate
            docker compose exec -T web python backend/manage.py collectstatic --noinput
            docker image prune -f